name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/shared-test.yml
    with:
      go-version: '1.24.3'

  security:
    name: Security
    uses: ./.github/workflows/shared-security.yml
    with:
      go-version: '1.24.3'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, security]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.3'

    - name: Download dependencies
      run: make deps

    - name: Build binary (linux-amd64)
      run: make build