name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.3'

    - name: Download dependencies
      run: make deps

    - name: Check formatting
      run: |
        make fmt
        if [ -n "$(git diff --exit-code)" ]; then
          echo "Code is not formatted. Run 'make fmt' to fix."
          exit 1
        fi

    - name: Run tests
      run: make test

    - name: Run tests with coverage
      run: make test-coverage

    - name: Run linter
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest

  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.3'

    - name: Verify dependencies
      run: go mod verify

    - name: Run gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: './...'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, security]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.3'

    - name: Download dependencies
      run: make deps

    - name: Build binary (linux-amd64)
      run: make build